#1)-Importing Libraries

In [1]:
import numpy as np

#2)-Spectral matrix decomposition

In [2]:
A = np.array([[3,2],
              [4,1]])
print(A)

[[3 2]
 [4 1]]


In [3]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [6]:
V = eigenvectors
lamb = np.diag(eigenvalues)
I_v = np.linalg.inv(V)

In [7]:
A_calc = V.dot(lamb).dot(I_v)
print(A_calc)

[[3. 2.]
 [4. 1.]]


A must be a real an symmetric matrix.

In [8]:
A = np.array([[3,2],
              [2,3]])
print(A)
print(A==A.T)

[[3 2]
 [2 3]]
[[ True  True]
 [ True  True]]


In [15]:
lamb, V = np.linalg.eig(A)
diag_lamb = np.diag(lamb)
print(V)
print(lamb)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[5. 1.]


In [16]:
A_cal = V.dot(diag_lamb).dot(V.T)
print(A_cal)

[[3. 2.]
 [2. 3.]]
