#1)-Importing Libraries

In [1]:
import numpy as np

#2)-SVD for non-squared matrices

1. U must be an orthonormal matrix where its columns are the singular left vectors of the original matriz.
2. V must be a orthonormal matrix where its columns are the singular right  vectors of the original matrix.
3. D is a diagonal matrix composed of the calculated singular values.

In [7]:
A = np.array([[1,2,3],
              [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [8]:
U, D, V = np.linalg.svd(A)
D = np.diag(D)
print(U)
print(D)
print(V)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]
[[7.97638869 0.        ]
 [0.         0.61418515]]
[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [9]:
A_cal = U.dot(D.dot(V))
print(A_cal)

ValueError: ignored